### Get list of alerts in prometheus
GET http://localhost:3000/api/prometheus/grafana/api/v1/alerts
Authorization: Basic {{username}} {{password}}

###  Get list of alets in alert manager
GET http://localhost:3000/api/alertmanager/grafana/config/api/v1/alerts
Authorization: Basic {{username}} {{password}}


### Rules
GET http://localhost:3000/api/ruler/grafana/api/v1/rules
Authorization: Basic {{username}} {{password}}

###
GET http://localhost:3000/api/ruler/grafana/api/v1/rules/MAAC demo/
Authorization: Basic {{username}} {{password}}

### List datasources
GET http://localhost:3000/api/datasources
Authorization: Basic {{username}} {{password}}


###
POST http://localhost:3000/api/ruler/grafana/api/v1/rules/MAAC demo/
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "interval": 40,
  "name": "WatchEye Alert",
  "rules": [
    {
      "alert": "WatchEye alert",
      "annotations": {
        "WE_ann": "lol"
      },
      "expr": null,
      "for": "5m",
      "grafana_alert": {
        "condition": "B",
        "data": [
          {
            "datasourceUid": "UyZh4UK7z",
            "model": {
              "refId": "A",
              "expr": "scrape_duration_seconds{instance=\"prometheus-data-generator:9000\"}",
              "interval": "",
              "intervalMs": 1000,
              "legendFormat": "",
              "maxDataPoints": 43200
            },
            "queryType": null,
            "refId": "A",
            "relativeTimeRange": {
              "from": 600.0,
              "to": 0.0
            }
          },
          {
            "datasourceUid": "-100",
            "model": {
              "intervalMs": 1000,
              "maxDataPoints": 43200,
              "type": "classic_conditions",
              "datasource": "__expr__",
              "conditions": [
                {
                  "evaluator": {
                    "params": [
                      0.01
                    ],
                    "type": "gt"
                  },
                  "operator": {
                    "type": "and"
                  },
                  "query": {
                    "params": [
                      "A"
                    ]
                  },
                  "reducer": {
                    "params": [],
                    "type": "last"
                  },
                  "type": "query"
                }
              ]
            },
            "queryType": null,
            "refId": "B",
            "relativeTimeRange": {
              "from": 0,
              "to": 0
            }
          }
        ],
        "exec_err_state": "Alerting",
        "no_data_state": "Alerting",
        "title": "WE_GrafanaAlertTitle",
        "uid": null
      },
      "labels": {
        "lb1": "val"
      },
      "record": null
    }
  ]
}

### Valid example
POST http://localhost:3000/api/ruler/grafana/api/v1/rules/MAAC demo/
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "name": "Generated Alert",
  "interval": "1m",
  "rules": [
    {
      "alert": "test_alert",
      "annotations": {
        "ann1": "val1"
      },
      "expr": "",
      "for": "5m",
      "labels": {
        "label1": "LabelVal1"
      },
      "grafana_alert": {
        "condition": "B",
        "title": "GrafanaAlertTitle",
        "exec_err_state": "Alerting",
        "no_data_state": "Alerting",
        "data": [
          {
            "refId": "A",
            "datasourceUid": "UyZh4UK7z",
            "relativeTimeRange": {
              "from": 600,
              "to": 0
            },
            "queryType": "",
            "model": {
              "refId": "A",
              "expr": "scrape_duration_seconds{instance=\"prometheus-data-generator:9000\"}",
              "interval": "",
              "intervalMs": 1000,
              "legendFormat": "",
              "maxDataPoints": 43200
            }
          },
          {
            "refId": "B",
            "queryType": "",
            "relativeTimeRange": {
              "from": 0,
              "to": 0
            },
            "datasourceUid": "-100",
            "model": {
              "intervalMs": 1000,
              "maxDataPoints": 43200,
              "type": "classic_conditions",
              "datasource": "__expr__",
              "conditions": [
                {
                  "evaluator": {
                    "params": [
                      0.01
                    ],
                    "type": "gt"
                  },
                  "operator": {
                    "type": "and"
                  },
                  "query": {
                    "params": [
                      "A"
                    ]
                  },
                  "reducer": {
                    "params": [],
                    "type": "last"
                  },
                  "type": "query"
                }
              ]
            }
          }
        ]
      }
    }
  ]
}